print("Word Problem 1")
print("If a group of 5 students work on a project for 70 hours and they")
print("split the work evenly, how many hours does each student work?")
input("Press enter to find out.")
print("70 / 5 =", 70 // 5)
print("")

print("Word Problem 2")
print("If George orders 6 whole pizza cut into 12 slices each")
print("and he wants to eat pizza every day for the next 10 days")
print("how many slices of pizza should he eat per day?")
input("Press enter to find out.")
print("6 * 12 / 10 =", 6 * 12 / 10)
print("")

print("Word Problem 3")
print("Johnny wants to give his mother flowers for Mothers' Day.")
print("When he went to the flower shop, he saw that they had 200 flowers.")
print("Half of them were yellow and half of them were red.")
print("His mother likes red and yellow flowers the best.")
print("If Johnny wants to give his mother 20 flowers, how many of each color")
print("should he get?")
answer = input("Please input your answer here.")
print("answer")
if answer == "10":
    print("Correct")
else:
    print("Wrong")
input("Press enter to check your answer")
print("If one color is half of the total amount of flowers")
print("then each color needs to be half of the desired amount")
print("of 20.  Therefore, Johnny needs 10 red flowers and 10 yellow flowers")
print("")

print("Word Problem 4")
print("Holly works for a catering company and she has to set out plates for")
print("a wedding reception.  If there are 30 tables that seat 8 people each")
print("and Holly has 2 hours to set up, how many plates must she set every")
print("10 minutes?")
answer = input("Please input your answer here.")
print("answer")
if answer == "20":
    print("Correct")
else:
    print("Wrong")
input("Press enter to check your answer")
print("30 * 8 / 12 =", 30 * 8 / 12)
print("")

print("Word Problem 5")
print("Hank and Julia decide to make pasta to share with their neighbors.")
print("They decide to make 30 pounds of pasta.  If half a pound of pasta can")
print("can fit into a Tupperware container, how many neighbors can Hank and")
print("Julia give pasta to if they give one container to each neighbor?")
input("Press enter to find out.")
print("30 * 2 =", 30 * 2)
